In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np


In [2]:
t= torch.tensor([1,2,3,4,5,6,7,8,9,10],dtype=torch.float32)

In [3]:
device= torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu')

In [4]:
device

device(type='mps')

In [5]:
t.to(device)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], device='mps:0')

In [6]:
x= torch.tensor([1,2,3,4,5],dtype=torch.float32,requires_grad=True)
y=torch.sum(x**2)

In [7]:
y.backward()


In [8]:
x.grad


tensor([ 2.,  4.,  6.,  8., 10.])

In [25]:
# implement gradient descent in torch
from torch import ones_like


x= torch.tensor([1,2,3,4,5],dtype=torch.float32,requires_grad=True)
weights = torch.tensor([0.1,0.2,0.3,0.4,0.5],dtype=torch.float32,requires_grad=True)
y=x@weights.T
weights_prime= ones_like(weights,requires_grad=True)
optimizer = optim.SGD([weights_prime], lr=0.01,)

def train_step(x, weights_prime, optimizer):
    optimizer.zero_grad()
    y_pred = x @ weights_prime.T
    loss = torch.sqrt(torch.mean((y_pred - y) ** 2))  # RMSE
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    # loss.backward()
    return loss.item()

# Training loop
for epoch in range(1000):
    loss = train_step(x, weights_prime, optimizer)
    if epoch % 100 == 0:
        print(f'Epoch {epoch}, Loss: {loss}')


Epoch 0, Loss: 9.5


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [54]:
import torch
import torch.optim as optim

# Make x and weights non-trainable for generating y
x = torch.tensor([1,2,3,4,5], dtype=torch.float32)
weights = torch.tensor([0.1,0.2,0.3,0.4,0.5], dtype=torch.float32)
y = (x @ weights.T).detach()

weights_prime = torch.zeros_like(weights, requires_grad=True)
optimizer = optim.SGD([weights_prime], lr=0.001)

def train_step(x, weights_prime, optimizer, y):
    optimizer.zero_grad()
    y_pred = x @ weights_prime.T
    loss = torch.sqrt(((y_pred - y) ** 2))
    print(f"{loss=}")
    loss.backward()
    print(f"{weights_prime.grad=}")
    print(f"{weights_prime=}")
    optimizer.step()
    return loss.item()

for epoch in range(1000): 
    loss = train_step(x, weights_prime, optimizer, y)
    if loss < 1e-5:
        break
    if epoch % 100 == 0:
        print(f'Epoch {epoch}, Loss: {loss}')
        print(weights_prime)

loss=tensor(5.5000, grad_fn=<SqrtBackward0>)
weights_prime.grad=tensor([-1., -2., -3., -4., -5.])
weights_prime=tensor([0., 0., 0., 0., 0.], requires_grad=True)
Epoch 0, Loss: 5.5
tensor([0.0010, 0.0020, 0.0030, 0.0040, 0.0050], requires_grad=True)
loss=tensor(5.4450, grad_fn=<SqrtBackward0>)
weights_prime.grad=tensor([-1., -2., -3., -4., -5.])
weights_prime=tensor([0.0010, 0.0020, 0.0030, 0.0040, 0.0050], requires_grad=True)
loss=tensor(5.3900, grad_fn=<SqrtBackward0>)
weights_prime.grad=tensor([-1.0000, -2.0000, -3.0000, -4.0000, -5.0000])
weights_prime=tensor([0.0020, 0.0040, 0.0060, 0.0080, 0.0100], requires_grad=True)
loss=tensor(5.3350, grad_fn=<SqrtBackward0>)
weights_prime.grad=tensor([-1., -2., -3., -4., -5.])
weights_prime=tensor([0.0030, 0.0060, 0.0090, 0.0120, 0.0150], requires_grad=True)
loss=tensor(5.2800, grad_fn=<SqrtBackward0>)
weights_prime.grad=tensor([-1., -2., -3., -4., -5.])
weights_prime=tensor([0.0040, 0.0080, 0.0120, 0.0160, 0.0200], requires_grad=True)
loss=te

In [47]:
weights_prime

tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [48]:
weights

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000])